TODO: move this into the right place (notebooks are just for figures as I understand it)

In [1]:
import multiprocessing
import os
import platform
from pathlib import Path

import numpy as np
import openscm_units
import pandas as pd
import pandas_indexing as pix
import pandas_openscm
import pint
from pandas_openscm.index_manipulation import update_index_levels_func

from gcages.cmip7_scenariomip.harmonisation import (
    create_cmip7_scenariomip_global_harmoniser,
    load_cmip7_scenariomip_historical_emissions,
)
from gcages.cmip7_scenariomip.infilling import (
    CMIP7ScenarioMIPInfiller,
    load_cmip7_scenariomip_ghg_inversions,
    load_cmip7_scenariomip_historical_emissions,
    load_cmip7_scenariomip_infilling_db,
)
from gcages.cmip7_scenariomip.harmonisation import load_cmip7_scenariomip_historical_emissions, load_aneris_overrides_file
from gcages.harmonisation.aneris import AnerisHarmoniser
from gcages.cmip7_scenariomip.post_processing import CMIP7ScenarioMIPPostProcessor
from gcages.cmip7_scenariomip.scm_running import CMIP7ScenarioMIPSCMRunner
from gcages.harmonisation.common import assert_harmonised
from gcages.renaming import (
    SupportedNamingConventions,
    convert_variable_name,
    rename_variables,
)
from gcages.units_helpers import strip_pint_incompatible_characters_from_units

In [2]:
pint.set_application_registry(openscm_units.unit_registry)

In [3]:
pandas_openscm.register_pandas_accessors()

In [4]:
feather_file = Path("emissions.feather")
if feather_file.exists():
    # Shortcut
    emissions = pd.read_feather(feather_file)
    
else:
    # Unclear if we can commit this file or not. Ignoring for now.
    start = pd.read_excel("SCI-2025_v1.0_pathways_ensemble_global.xlsx", sheet_name="data")
    tmp = start.copy()
    tmp.columns = tmp.columns.str.lower()
    tmp = tmp.set_index(["model", "scenario", "region", "variable", "unit"])
    emissions = tmp.loc[pix.ismatch(variable="Emissions**", region="World")]
    emissions.to_feather(feather_file)

emissions.columns = emissions.columns.astype(int)
emissions

                                                                                           2010  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             7.337400
                                            Emissions|CH4         Mt CH4/yr          368.104600
                                            Emissions|CH4|AFOLU   Mt CH4/yr          179.530900
                                            Emissions|CH4|Energy  Mt CH4/yr          124.394400
                                            Emissions|CO          Mt CO/yr           870.610400
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   1032.189454
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  48676.563680
                                            Emissions|N2O         kt N2O/yr        10235.569004
                                            Emissions|N2O|AFOLU   kt N2O/yr         8779.675302
                                            Emissions|Sulfur      Mt SO2/yr           81.655701

                                                                                           2015  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             6.661400
                                            Emissions|CH4         Mt CH4/yr          371.281100
                                            Emissions|CH4|AFOLU   Mt CH4/yr          184.616800
                                            Emissions|CH4|Energy  Mt CH4/yr          120.509300
                                            Emissions|CO          Mt CO/yr           818.449800
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   1872.142705
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  52097.101002
                                            Emissions|N2O         kt N2O/yr        10330.054024
                                            Emissions|N2O|AFOLU   kt N2O/yr         8850.331096
                                            Emissions|Sulfur      Mt SO2/yr           84.329131

                                                                                           2020  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             5.985400
                                            Emissions|CH4         Mt CH4/yr          374.457600
                                            Emissions|CH4|AFOLU   Mt CH4/yr          189.702700
                                            Emissions|CH4|Energy  Mt CH4/yr          116.624200
                                            Emissions|CO          Mt CO/yr           766.289200
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   2642.220050
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  58277.316825
                                            Emissions|N2O         kt N2O/yr        10596.100239
                                            Emissions|N2O|AFOLU   kt N2O/yr         8996.243223
                                            Emissions|Sulfur      Mt SO2/yr           82.158099

                                                                                           2025  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             5.058750
                                            Emissions|CH4         Mt CH4/yr          251.807950
                                            Emissions|CH4|AFOLU   Mt CH4/yr          141.593500
                                            Emissions|CH4|Energy  Mt CH4/yr           68.747700
                                            Emissions|CO          Mt CO/yr           695.306350
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   1685.818180
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  62906.953037
                                            Emissions|N2O         kt N2O/yr        10776.156593
                                            Emissions|N2O|AFOLU   kt N2O/yr         9072.874175
                                            Emissions|Sulfur      Mt SO2/yr           80.830597

                                                                                           2030  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             4.132100
                                            Emissions|CH4         Mt CH4/yr          129.158300
                                            Emissions|CH4|AFOLU   Mt CH4/yr           93.484300
                                            Emissions|CH4|Energy  Mt CH4/yr           20.871200
                                            Emissions|CO          Mt CO/yr           624.323500
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   1828.847710
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  68244.591083
                                            Emissions|N2O         kt N2O/yr        10916.094262
                                            Emissions|N2O|AFOLU   kt N2O/yr         9109.855561
                                            Emissions|Sulfur      Mt SO2/yr           77.234362

                                                                                           2035  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             3.794600
                                            Emissions|CH4         Mt CH4/yr          113.003800
                                            Emissions|CH4|AFOLU   Mt CH4/yr           83.234100
                                            Emissions|CH4|Energy  Mt CH4/yr           17.688100
                                            Emissions|CO          Mt CO/yr           586.274750
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   1974.868733
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  72744.941643
                                            Emissions|N2O         kt N2O/yr        10948.119475
                                            Emissions|N2O|AFOLU   kt N2O/yr         9049.407914
                                            Emissions|Sulfur      Mt SO2/yr           70.622733

                                                                                           2040  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             3.457100
                                            Emissions|CH4         Mt CH4/yr           96.849300
                                            Emissions|CH4|AFOLU   Mt CH4/yr           72.983900
                                            Emissions|CH4|Energy  Mt CH4/yr           14.505000
                                            Emissions|CO          Mt CO/yr           548.226000
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   2131.559351
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  76878.499006
                                            Emissions|N2O         kt N2O/yr        10933.624738
                                            Emissions|N2O|AFOLU   kt N2O/yr         8952.379387
                                            Emissions|Sulfur      Mt SO2/yr           61.623144

                                                                                           2045  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             3.215150
                                            Emissions|CH4         Mt CH4/yr           84.507100
                                            Emissions|CH4|AFOLU   Mt CH4/yr           64.365000
                                            Emissions|CH4|Energy  Mt CH4/yr           12.611000
                                            Emissions|CO          Mt CO/yr           514.563750
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   2295.428499
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  80290.099430
                                            Emissions|N2O         kt N2O/yr        10805.811037
                                            Emissions|N2O|AFOLU   kt N2O/yr         8744.704433
                                            Emissions|Sulfur      Mt SO2/yr           50.204812

                                                                                           2050  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             2.973200
                                            Emissions|CH4         Mt CH4/yr           72.164900
                                            Emissions|CH4|AFOLU   Mt CH4/yr           55.746100
                                            Emissions|CH4|Energy  Mt CH4/yr           10.717000
                                            Emissions|CO          Mt CO/yr           480.901500
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   2456.616846
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  83318.105577
                                            Emissions|N2O         kt N2O/yr        10625.859542
                                            Emissions|N2O|AFOLU   kt N2O/yr         8504.449498
                                            Emissions|Sulfur      Mt SO2/yr           36.489424

                                                                                   2055  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr          NaN
                                            Emissions|CH4         Mt CH4/yr         NaN
                                            Emissions|CH4|AFOLU   Mt CH4/yr         NaN
                                            Emissions|CH4|Energy  Mt CH4/yr         NaN
                                            Emissions|CO          Mt CO/yr          NaN
...                                                                                 ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   NaN
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr   NaN
                                            Emissions|N2O         kt N2O/yr         NaN
                                            Emissions|N2O|AFOLU   kt N2O/yr         NaN
                                            Emissions|Sulfur      Mt SO2/yr         NaN

                                                                                           2060  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             2.753300
                                            Emissions|CH4         Mt CH4/yr           61.704000
                                            Emissions|CH4|AFOLU   Mt CH4/yr           49.746600
                                            Emissions|CH4|Energy  Mt CH4/yr            7.591500
                                            Emissions|CO          Mt CO/yr           448.919100
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   2770.367316
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  88976.044473
                                            Emissions|N2O         kt N2O/yr        11038.800399
                                            Emissions|N2O|AFOLU   kt N2O/yr         8855.393953
                                            Emissions|Sulfur      Mt SO2/yr           32.966164

                                                                                   2065  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr          NaN
                                            Emissions|CH4         Mt CH4/yr         NaN
                                            Emissions|CH4|AFOLU   Mt CH4/yr         NaN
                                            Emissions|CH4|Energy  Mt CH4/yr         NaN
                                            Emissions|CO          Mt CO/yr          NaN
...                                                                                 ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   NaN
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr   NaN
                                            Emissions|N2O         kt N2O/yr         NaN
                                            Emissions|N2O|AFOLU   kt N2O/yr         NaN
                                            Emissions|Sulfur      Mt SO2/yr         NaN

                                                                                           2070  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             2.555100
                                            Emissions|CH4         Mt CH4/yr           57.213400
                                            Emissions|CH4|AFOLU   Mt CH4/yr           47.330000
                                            Emissions|CH4|Energy  Mt CH4/yr            6.018100
                                            Emissions|CO          Mt CO/yr           417.698700
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   3136.375448
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  94872.558307
                                            Emissions|N2O         kt N2O/yr        11330.244915
                                            Emissions|N2O|AFOLU   kt N2O/yr         9100.782293
                                            Emissions|Sulfur      Mt SO2/yr           32.053593

                                                                                   2075  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr          NaN
                                            Emissions|CH4         Mt CH4/yr         NaN
                                            Emissions|CH4|AFOLU   Mt CH4/yr         NaN
                                            Emissions|CH4|Energy  Mt CH4/yr         NaN
                                            Emissions|CO          Mt CO/yr          NaN
...                                                                                 ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   NaN
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr   NaN
                                            Emissions|N2O         kt N2O/yr         NaN
                                            Emissions|N2O|AFOLU   kt N2O/yr         NaN
                                            Emissions|Sulfur      Mt SO2/yr         NaN

                                                                                           2080  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr             2.381400
                                            Emissions|CH4         Mt CH4/yr           53.090800
                                            Emissions|CH4|AFOLU   Mt CH4/yr           44.823400
                                            Emissions|CH4|Energy  Mt CH4/yr            4.814300
                                            Emissions|CO          Mt CO/yr           389.227100
...                                                                                         ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   3450.813167
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr  99925.221682
                                            Emissions|N2O         kt N2O/yr        11473.853958
                                            Emissions|N2O|AFOLU   kt N2O/yr         9265.277768
                                            Emissions|Sulfur      Mt SO2/yr           30.864629

                                                                                   2085  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr          NaN
                                            Emissions|CH4         Mt CH4/yr         NaN
                                            Emissions|CH4|AFOLU   Mt CH4/yr         NaN
                                            Emissions|CH4|Energy  Mt CH4/yr         NaN
                                            Emissions|CO          Mt CO/yr          NaN
...                                                                                 ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|F-Gases     Mt CO2-equiv/yr   NaN
                                            Emissions|Kyoto Gases Mt CO2-equiv/yr   NaN
                                            Emissions|N2O         kt N2O/yr         NaN
                                            Emissions|N2O|AFOLU   kt N2O/yr         NaN
                                            Emissions|Sulfur      Mt SO2/yr         NaN

                                                                                            2090  \
model             scenario           region variable              unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC          Mt BC/yr              2.210800
                                            Emissions|CH4         Mt CH4/yr            51.013900
                                            Emissions|CH4|AFOLU   Mt CH4/yr            43.586500
                                            Emissions|CH4|Energy  Mt CH4/yr             4.112900
                                            Emissions|CO          Mt CO/yr            360.707100

## Various hacks to the input

All the usual things that are needed to deal with IAM data.

In [5]:
emissions = emissions.sort_index(axis="columns")

unusable_too_late_start = (
    emissions.isnull()
    .idxmin(axis="columns")
    .groupby(["model", "scenario"])
    .max()
    .sort_values()
)
unusable_too_late_start = unusable_too_late_start[unusable_too_late_start > 2023]
print(f"Unusuable because they start after 2023:\n{unusable_too_late_start}")
emissions_usable = emissions.loc[
    ~pandas_openscm.indexing.multi_index_match(
        emissions.index,
        unusable_too_late_start.index,
    )
]

for y in range(2010, 2100 + 1):
    if y not in emissions_usable:
        emissions_usable[y] = np.nan
        
emissions = (
    emissions_usable.T.interpolate(method="index")
    .T.sort_index(axis="columns")
    .loc[:, 2023:]
)
if emissions.isnull().any().any():
    raise AssertionError

Unusuable because they start after 2023:
model                  scenario
MESSAGEix-GLOBIOM 1.1  GENIE DACCS DACm-LP-median-stor3-final_700                     2025
                       GENIE DACCS DACl-MP-median-stor3-final_500                     2025
                       GENIE DACCS DACm-MP-median-stor3-phs-govmSSP2-CO2total_1000    2025
                       GENIE DACCS DACm-MP-median-stor3-phs-govmSSP1-CO2total_700     2025
                       GENIE DACCS DACm-MP-median-stor3-phs-govmSSP1-CO2total_1000    2025
                       GENIE DACCS DACm-MP-median-stor3-final_700                     2025
                       GENIE DACCS DACm-MP-median-stor3-final_500                     2025
                       GENIE DACCS DACm-MP-median-stor3-final_1000                    2025
                       GENIE DACCS DACm-LP-median-stor3-phs-govmSSP2-CO2total_1000    2025
                       GENIE DACCS DACm-LP-median-stor3-phs-govmSSP1-CO2total_700     2025
                       GENIE DACCS DACm-LP-median-stor3-final_500                     2025
                       GENIE DACCS DACm-LP-median-stor3-final_1000                    2025
                       GENIE DACCS DACm-HP-median-stor3-phs-govmSSP2-CO2total_1000    2025
                       GENIE DACCS DACm-HP-median-stor3-phs-govmSSP1-CO2total_700     2025
                       GENIE DACCS DACm-HP-median-stor3-phs-govmSSP1-CO2total_1000    2025
                       GENIE DACCS DACm-HP-median-stor3-final_700                     2025
                       GENIE DACCS DACm-HP-median-stor3-final_500                     2025
                       GENIE DACCS DACm-HP-median-stor3-final_1000                    2025
                       GENIE DACCS DACl-MP-median-stor3-final_700                     2025
                       GENIE DACCS DACl-MP-median-stor3-final_1000                    2025
                       GENIE DACCS DACm-LP-median-stor3-phs-govmSSP1-CO2total_1000    2025
dtype: int64

In [6]:
emissions_renamed = rename_variables(
    emissions.loc[
        pix.ismatch(
            variable=[
                "Emissions|*",
                "Emissions|HFC|**",
                # Almost certainly need some reaggregation for some scenarios
                "Emissions|CO2|Energy and Industrial Processes",
                "Emissions|CO2|AFOLU",
            ]
        )
        & ~pix.isin(
            variable=[
                "Emissions|F-Gases",
                "Emissions|PFC",
                "Emissions|HFC",
                "Emissions|Kyoto Gases",
                "Emissions|CO2",
            ]
        )
    ],
    from_convention=SupportedNamingConventions.CMIP7_SCENARIOMIP,
    to_convention=SupportedNamingConventions.GCAGES,
)
emissions_renamed = strip_pint_incompatible_characters_from_units(
    emissions_renamed, units_index_level="unit"
)

sorted(emissions_renamed.index.droplevel(["model", "scenario", "region"]).unique())

[('Emissions|BC', 'Mt BC/yr'),
 ('Emissions|C2F6', 'kt C2F6/yr'),
 ('Emissions|C6F14', 'kt C6F14/yr'),
 ('Emissions|CF4', 'kt CF4/yr'),
 ('Emissions|CH4', 'Mt CH4/yr'),
 ('Emissions|CO', 'Mt CO/yr'),
 ('Emissions|CO2|Biosphere', 'Mt CO2/yr'),
 ('Emissions|CO2|Fossil', 'Mt CO2/yr'),
 ('Emissions|HFC125', 'kt HFC125/yr'),
 ('Emissions|HFC134a', 'kt HFC134a/yr'),
 ('Emissions|HFC143a', 'kt HFC143a/yr'),
 ('Emissions|HFC227ea', 'kt HFC227ea/yr'),
 ('Emissions|HFC23', 'kt HFC23/yr'),
 ('Emissions|HFC245fa', 'kt HFC245fa/yr'),
 ('Emissions|HFC32', 'kt HFC32/yr'),
 ('Emissions|HFC4310mee', 'kt HFC4310/yr'),
 ('Emissions|N2O', 'kt N2O/yr'),
 ('Emissions|NH3', 'Mt NH3/yr'),
 ('Emissions|NMVOC', 'Mt VOC/yr'),
 ('Emissions|NOx', 'Mt NO2/yr'),
 ('Emissions|OC', 'Mt OC/yr'),
 ('Emissions|SF6', 'kt SF6/yr'),
 ('Emissions|SOx', 'Mt SO2/yr')]

In [7]:
run_all = True
# run_all = False
if run_all:
    emissions_run = emissions_renamed
    
else:
    models_included = []
    new_idx_levels = []
    for model, scenario in emissions_renamed.index.droplevel(
        ["region", "variable", "unit"]
    ).unique():
        if model in models_included:
            continue

        models_included.append(model)
        new_idx_levels.append((model, scenario))

    emissions_run = emissions_renamed.loc[
        pandas_openscm.indexing.multi_index_match(
            emissions_renamed.index,
            pd.MultiIndex.from_tuples(new_idx_levels, names=["model", "scenario"]),
        )
    ]

    # emissions_run = emissions_run.loc[pix.isin(model="REMIND 2.1", scenario="R2p1-SSP2-1100")]
    
emissions_run

                                                                                       2023  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.429410
                                            Emissions|CH4           Mt CH4/yr    300.867810
                                            Emissions|CO            Mt CO/yr     723.699490
                                            Emissions|CO2|Biosphere Mt CO2/yr   2506.979860
                                            Emissions|CO2|Fossil    Mt CO2/yr  29273.990990
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    404.808829
                                            Emissions|CO2|Biosphere Mt CO2/yr   2660.334724
                                            Emissions|CO2|Fossil    Mt CO2/yr  43016.332284
                                            Emissions|N2O           kt N2O/yr  10704.134052
                                            Emissions|SOx           Mt SO2/yr     81.361598

                                                                                       2024  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.244080
                                            Emissions|CH4           Mt CH4/yr    276.337880
                                            Emissions|CO            Mt CO/yr     709.502920
                                            Emissions|CO2|Biosphere Mt CO2/yr   2138.037580
                                            Emissions|CO2|Fossil    Mt CO2/yr  27825.293620
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    408.792866
                                            Emissions|CO2|Biosphere Mt CO2/yr   2663.847629
                                            Emissions|CO2|Fossil    Mt CO2/yr  44019.694709
                                            Emissions|N2O           kt N2O/yr  10740.145323
                                            Emissions|SOx           Mt SO2/yr     81.096097

                                                                                       2025  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.058750
                                            Emissions|CH4           Mt CH4/yr    251.807950
                                            Emissions|CO            Mt CO/yr     695.306350
                                            Emissions|CO2|Biosphere Mt CO2/yr   1769.095300
                                            Emissions|CO2|Fossil    Mt CO2/yr  26376.596250
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    412.776903
                                            Emissions|CO2|Biosphere Mt CO2/yr   2667.360534
                                            Emissions|CO2|Fossil    Mt CO2/yr  45023.057135
                                            Emissions|N2O           kt N2O/yr  10776.156593
                                            Emissions|SOx           Mt SO2/yr     80.830597

                                                                                       2026  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.873420
                                            Emissions|CH4           Mt CH4/yr    227.278020
                                            Emissions|CO            Mt CO/yr     681.109780
                                            Emissions|CO2|Biosphere Mt CO2/yr   1400.153020
                                            Emissions|CO2|Fossil    Mt CO2/yr  24927.898880
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    415.969747
                                            Emissions|CO2|Biosphere Mt CO2/yr   2673.467674
                                            Emissions|CO2|Fossil    Mt CO2/yr  45967.710329
                                            Emissions|N2O           kt N2O/yr  10804.144127
                                            Emissions|SOx           Mt SO2/yr     80.111350

                                                                                       2027  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.688090
                                            Emissions|CH4           Mt CH4/yr    202.748090
                                            Emissions|CO            Mt CO/yr     666.913210
                                            Emissions|CO2|Biosphere Mt CO2/yr   1031.210740
                                            Emissions|CO2|Fossil    Mt CO2/yr  23479.201510
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    419.162591
                                            Emissions|CO2|Biosphere Mt CO2/yr   2679.574814
                                            Emissions|CO2|Fossil    Mt CO2/yr  46912.363522
                                            Emissions|N2O           kt N2O/yr  10832.131661
                                            Emissions|SOx           Mt SO2/yr     79.392103

                                                                                       2028  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.502760
                                            Emissions|CH4           Mt CH4/yr    178.218160
                                            Emissions|CO            Mt CO/yr     652.716640
                                            Emissions|CO2|Biosphere Mt CO2/yr    662.268460
                                            Emissions|CO2|Fossil    Mt CO2/yr  22030.504140
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    422.355434
                                            Emissions|CO2|Biosphere Mt CO2/yr   2685.681954
                                            Emissions|CO2|Fossil    Mt CO2/yr  47857.016716
                                            Emissions|N2O           kt N2O/yr  10860.119194
                                            Emissions|SOx           Mt SO2/yr     78.672856

                                                                                       2029  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.317430
                                            Emissions|CH4           Mt CH4/yr    153.688230
                                            Emissions|CO            Mt CO/yr     638.520070
                                            Emissions|CO2|Biosphere Mt CO2/yr    293.326180
                                            Emissions|CO2|Fossil    Mt CO2/yr  20581.806770
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    425.548278
                                            Emissions|CO2|Biosphere Mt CO2/yr   2691.789094
                                            Emissions|CO2|Fossil    Mt CO2/yr  48801.669910
                                            Emissions|N2O           kt N2O/yr  10888.106728
                                            Emissions|SOx           Mt SO2/yr     77.953609

                                                                                       2030  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.132100
                                            Emissions|CH4           Mt CH4/yr    129.158300
                                            Emissions|CO            Mt CO/yr     624.323500
                                            Emissions|CO2|Biosphere Mt CO2/yr    -75.616100
                                            Emissions|CO2|Fossil    Mt CO2/yr  19133.109400
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    428.741121
                                            Emissions|CO2|Biosphere Mt CO2/yr   2697.896235
                                            Emissions|CO2|Fossil    Mt CO2/yr  49746.323103
                                            Emissions|N2O           kt N2O/yr  10916.094262
                                            Emissions|SOx           Mt SO2/yr     77.234362

                                                                                       2031  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.064600
                                            Emissions|CH4           Mt CH4/yr    125.927400
                                            Emissions|CO            Mt CO/yr     616.713750
                                            Emissions|CO2|Biosphere Mt CO2/yr   -338.679840
                                            Emissions|CO2|Fossil    Mt CO2/yr  18313.355810
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    431.180084
                                            Emissions|CO2|Biosphere Mt CO2/yr   2663.701714
                                            Emissions|CO2|Fossil    Mt CO2/yr  50588.500773
                                            Emissions|N2O           kt N2O/yr  10922.499304
                                            Emissions|SOx           Mt SO2/yr     75.912036

                                                                                       2032  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       3.997100
                                            Emissions|CH4           Mt CH4/yr    122.696500
                                            Emissions|CO            Mt CO/yr     609.104000
                                            Emissions|CO2|Biosphere Mt CO2/yr   -601.743580
                                            Emissions|CO2|Fossil    Mt CO2/yr  17493.602220
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    433.619047
                                            Emissions|CO2|Biosphere Mt CO2/yr   2629.507194
                                            Emissions|CO2|Fossil    Mt CO2/yr  51430.678442
                                            Emissions|N2O           kt N2O/yr  10928.904347
                                            Emissions|SOx           Mt SO2/yr     74.589710

                                                                               ...  \
model             scenario           region variable                unit       ...
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr   ...
                                            Emissions|CH4           Mt CH4/yr  ...
                                            Emissions|CO            Mt CO/yr   ...
                                            Emissions|CO2|Biosphere Mt CO2/yr  ...
                                            Emissions|CO2|Fossil    Mt CO2/yr  ...
...                                                                            ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr  ...
                                            Emissions|CO2|Biosphere Mt CO2/yr  ...
                                            Emissions|CO2|Fossil    Mt CO2/yr  ...
                                            Emissions|N2O           kt N2O/yr  ...
                                            Emissions|SOx           Mt SO2/yr  ...

                                                                                       2091  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.196800
                                            Emissions|CH4           Mt CH4/yr     50.610510
                                            Emissions|CO            Mt CO/yr     358.254100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3870.358180
                                            Emissions|CO2|Fossil    Mt CO2/yr   -528.572750
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    439.721131
                                            Emissions|CO2|Biosphere Mt CO2/yr    457.675862
                                            Emissions|CO2|Fossil    Mt CO2/yr  83348.742740
                                            Emissions|N2O           kt N2O/yr  11492.118111
                                            Emissions|SOx           Mt SO2/yr     28.914690

                                                                                       2092  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.182800
                                            Emissions|CH4           Mt CH4/yr     50.207120
                                            Emissions|CO            Mt CO/yr     355.801100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3841.854860
                                            Emissions|CO2|Fossil    Mt CO2/yr   -565.514200
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    437.216617
                                            Emissions|CO2|Biosphere Mt CO2/yr    462.995950
                                            Emissions|CO2|Fossil    Mt CO2/yr  82972.482440
                                            Emissions|N2O           kt N2O/yr  11471.374243
                                            Emissions|SOx           Mt SO2/yr     28.686702

                                                                                       2093  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.168800
                                            Emissions|CH4           Mt CH4/yr     49.803730
                                            Emissions|CO            Mt CO/yr     353.348100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3813.351540
                                            Emissions|CO2|Fossil    Mt CO2/yr   -602.455650
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    434.712103
                                            Emissions|CO2|Biosphere Mt CO2/yr    468.316037
                                            Emissions|CO2|Fossil    Mt CO2/yr  82596.222140
                                            Emissions|N2O           kt N2O/yr  11450.630376
                                            Emissions|SOx           Mt SO2/yr     28.458714

                                                                                       2094  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.154800
                                            Emissions|CH4           Mt CH4/yr     49.400340
                                            Emissions|CO            Mt CO/yr     350.895100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3784.848220
                                            Emissions|CO2|Fossil    Mt CO2/yr   -639.397100
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    432.207589
                                            Emissions|CO2|Biosphere Mt CO2/yr    473.636124
                                            Emissions|CO2|Fossil    Mt CO2/yr  82219.961841
                                            Emissions|N2O           kt N2O/yr  11429.886509
                                            Emissions|SOx           Mt SO2/yr     28.230726

                                                                                       2095  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.140800
                                            Emissions|CH4           Mt CH4/yr     48.996950
                                            Emissions|CO            Mt CO/yr     348.442100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3756.344900
                                            Emissions|CO2|Fossil    Mt CO2/yr   -676.338550
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    429.703076
                                            Emissions|CO2|Biosphere Mt CO2/yr    478.956212
                                            Emissions|CO2|Fossil    Mt CO2/yr  81843.701541
                                            Emissions|N2O           kt N2O/yr  11409.142642
                                            Emissions|SOx           Mt SO2/yr     28.002738

                                                                                       2096  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.126800
                                            Emissions|CH4           Mt CH4/yr     48.593560
                                            Emissions|CO            Mt CO/yr     345.989100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3727.841580
                                            Emissions|CO2|Fossil    Mt CO2/yr   -713.280000
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    427.198562
                                            Emissions|CO2|Biosphere Mt CO2/yr    484.276299
                                            Emissions|CO2|Fossil    Mt CO2/yr  81467.441241
                                            Emissions|N2O           kt N2O/yr  11388.398774
                                            Emissions|SOx           Mt SO2/yr     27.774750


In [8]:
# Round to get rid of spurious negatives
emissions_run.loc[
    pix.ismatch(variable="**HFC**")
    & (emissions_run.round(3) == 0.0).any(axis="columns")
] = 0.0
neg_vals = (emissions_run.loc[~pix.ismatch(variable="**CO2**")] < 0).any(axis=1)
unusable_because_of_neg = (
    neg_vals[neg_vals].index.droplevel(["region", "variable", "unit"]).drop_duplicates()
)
print(
    f"Unusuable because of inexplicable negatives:\n{emissions_run.loc[~pix.ismatch(variable='**CO2**')].loc[neg_vals].min(axis=1)}"
)

emissions_run = emissions_run.loc[
    ~pandas_openscm.indexing.multi_index_match(
        emissions_run.index, unusable_because_of_neg
    )
]
emissions_run

Unusuable because of inexplicable negatives:
model                          scenario                     region  variable           unit
MESSAGEix-GLOBIOM 1.1-BMT-R12  NAVIGATE Demand-1.5°C-all_u  World   Emissions|HFC125   kt HFC125/yr    -138.128465
                                                                    Emissions|HFC143a  kt HFC143a/yr     -3.408424
                                                                    Emissions|HFC32    kt HFC32/yr     -141.337757
                               NAVIGATE Demand-1.5°C-ref    World   Emissions|HFC125   kt HFC125/yr    -138.128465
                                                                    Emissions|HFC143a  kt HFC143a/yr     -3.408424
                                                                    Emissions|HFC32    kt HFC32/yr     -141.337757
                               NAVIGATE Demand-2.0°C-act_u  World   Emissions|HFC125   kt HFC125/yr     -49.451111
                               NAVIGATE Demand-2.0°C-all_u  World   Emissions|HFC125   kt HFC125/yr     -61.290757
                               NAVIGATE Demand-2.0°C-ele_u  World   Emissions|HFC125   kt HFC125/yr     -58.273480
                               NAVIGATE Demand-2.0°C-ref    World   Emissions|HFC125   kt HFC125/yr     -45.693163
                               NAVIGATE Demand-2.0°C-tec_u  World   Emissions|HFC125   kt HFC125/yr     -57.170456
dtype: float64

                                                                                       2023  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.429410
                                            Emissions|CH4           Mt CH4/yr    300.867810
                                            Emissions|CO            Mt CO/yr     723.699490
                                            Emissions|CO2|Biosphere Mt CO2/yr   2506.979860
                                            Emissions|CO2|Fossil    Mt CO2/yr  29273.990990
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    404.808829
                                            Emissions|CO2|Biosphere Mt CO2/yr   2660.334724
                                            Emissions|CO2|Fossil    Mt CO2/yr  43016.332284
                                            Emissions|N2O           kt N2O/yr  10704.134052
                                            Emissions|SOx           Mt SO2/yr     81.361598

                                                                                       2024  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.244080
                                            Emissions|CH4           Mt CH4/yr    276.337880
                                            Emissions|CO            Mt CO/yr     709.502920
                                            Emissions|CO2|Biosphere Mt CO2/yr   2138.037580
                                            Emissions|CO2|Fossil    Mt CO2/yr  27825.293620
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    408.792866
                                            Emissions|CO2|Biosphere Mt CO2/yr   2663.847629
                                            Emissions|CO2|Fossil    Mt CO2/yr  44019.694709
                                            Emissions|N2O           kt N2O/yr  10740.145323
                                            Emissions|SOx           Mt SO2/yr     81.096097

                                                                                       2025  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.058750
                                            Emissions|CH4           Mt CH4/yr    251.807950
                                            Emissions|CO            Mt CO/yr     695.306350
                                            Emissions|CO2|Biosphere Mt CO2/yr   1769.095300
                                            Emissions|CO2|Fossil    Mt CO2/yr  26376.596250
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    412.776903
                                            Emissions|CO2|Biosphere Mt CO2/yr   2667.360534
                                            Emissions|CO2|Fossil    Mt CO2/yr  45023.057135
                                            Emissions|N2O           kt N2O/yr  10776.156593
                                            Emissions|SOx           Mt SO2/yr     80.830597

                                                                                       2026  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.873420
                                            Emissions|CH4           Mt CH4/yr    227.278020
                                            Emissions|CO            Mt CO/yr     681.109780
                                            Emissions|CO2|Biosphere Mt CO2/yr   1400.153020
                                            Emissions|CO2|Fossil    Mt CO2/yr  24927.898880
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    415.969747
                                            Emissions|CO2|Biosphere Mt CO2/yr   2673.467674
                                            Emissions|CO2|Fossil    Mt CO2/yr  45967.710329
                                            Emissions|N2O           kt N2O/yr  10804.144127
                                            Emissions|SOx           Mt SO2/yr     80.111350

                                                                                       2027  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.688090
                                            Emissions|CH4           Mt CH4/yr    202.748090
                                            Emissions|CO            Mt CO/yr     666.913210
                                            Emissions|CO2|Biosphere Mt CO2/yr   1031.210740
                                            Emissions|CO2|Fossil    Mt CO2/yr  23479.201510
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    419.162591
                                            Emissions|CO2|Biosphere Mt CO2/yr   2679.574814
                                            Emissions|CO2|Fossil    Mt CO2/yr  46912.363522
                                            Emissions|N2O           kt N2O/yr  10832.131661
                                            Emissions|SOx           Mt SO2/yr     79.392103

                                                                                       2028  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.502760
                                            Emissions|CH4           Mt CH4/yr    178.218160
                                            Emissions|CO            Mt CO/yr     652.716640
                                            Emissions|CO2|Biosphere Mt CO2/yr    662.268460
                                            Emissions|CO2|Fossil    Mt CO2/yr  22030.504140
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    422.355434
                                            Emissions|CO2|Biosphere Mt CO2/yr   2685.681954
                                            Emissions|CO2|Fossil    Mt CO2/yr  47857.016716
                                            Emissions|N2O           kt N2O/yr  10860.119194
                                            Emissions|SOx           Mt SO2/yr     78.672856

                                                                                       2029  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.317430
                                            Emissions|CH4           Mt CH4/yr    153.688230
                                            Emissions|CO            Mt CO/yr     638.520070
                                            Emissions|CO2|Biosphere Mt CO2/yr    293.326180
                                            Emissions|CO2|Fossil    Mt CO2/yr  20581.806770
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    425.548278
                                            Emissions|CO2|Biosphere Mt CO2/yr   2691.789094
                                            Emissions|CO2|Fossil    Mt CO2/yr  48801.669910
                                            Emissions|N2O           kt N2O/yr  10888.106728
                                            Emissions|SOx           Mt SO2/yr     77.953609

                                                                                       2030  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.132100
                                            Emissions|CH4           Mt CH4/yr    129.158300
                                            Emissions|CO            Mt CO/yr     624.323500
                                            Emissions|CO2|Biosphere Mt CO2/yr    -75.616100
                                            Emissions|CO2|Fossil    Mt CO2/yr  19133.109400
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    428.741121
                                            Emissions|CO2|Biosphere Mt CO2/yr   2697.896235
                                            Emissions|CO2|Fossil    Mt CO2/yr  49746.323103
                                            Emissions|N2O           kt N2O/yr  10916.094262
                                            Emissions|SOx           Mt SO2/yr     77.234362

                                                                                       2031  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       4.064600
                                            Emissions|CH4           Mt CH4/yr    125.927400
                                            Emissions|CO            Mt CO/yr     616.713750
                                            Emissions|CO2|Biosphere Mt CO2/yr   -338.679840
                                            Emissions|CO2|Fossil    Mt CO2/yr  18313.355810
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    431.180084
                                            Emissions|CO2|Biosphere Mt CO2/yr   2663.701714
                                            Emissions|CO2|Fossil    Mt CO2/yr  50588.500773
                                            Emissions|N2O           kt N2O/yr  10922.499304
                                            Emissions|SOx           Mt SO2/yr     75.912036

                                                                                       2032  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       3.997100
                                            Emissions|CH4           Mt CH4/yr    122.696500
                                            Emissions|CO            Mt CO/yr     609.104000
                                            Emissions|CO2|Biosphere Mt CO2/yr   -601.743580
                                            Emissions|CO2|Fossil    Mt CO2/yr  17493.602220
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    433.619047
                                            Emissions|CO2|Biosphere Mt CO2/yr   2629.507194
                                            Emissions|CO2|Fossil    Mt CO2/yr  51430.678442
                                            Emissions|N2O           kt N2O/yr  10928.904347
                                            Emissions|SOx           Mt SO2/yr     74.589710

                                                                               ...  \
model             scenario           region variable                unit       ...
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr   ...
                                            Emissions|CH4           Mt CH4/yr  ...
                                            Emissions|CO            Mt CO/yr   ...
                                            Emissions|CO2|Biosphere Mt CO2/yr  ...
                                            Emissions|CO2|Fossil    Mt CO2/yr  ...
...                                                                            ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr  ...
                                            Emissions|CO2|Biosphere Mt CO2/yr  ...
                                            Emissions|CO2|Fossil    Mt CO2/yr  ...
                                            Emissions|N2O           kt N2O/yr  ...
                                            Emissions|SOx           Mt SO2/yr  ...

                                                                                       2091  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.196800
                                            Emissions|CH4           Mt CH4/yr     50.610510
                                            Emissions|CO            Mt CO/yr     358.254100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3870.358180
                                            Emissions|CO2|Fossil    Mt CO2/yr   -528.572750
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    439.721131
                                            Emissions|CO2|Biosphere Mt CO2/yr    457.675862
                                            Emissions|CO2|Fossil    Mt CO2/yr  83348.742740
                                            Emissions|N2O           kt N2O/yr  11492.118111
                                            Emissions|SOx           Mt SO2/yr     28.914690

                                                                                       2092  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.182800
                                            Emissions|CH4           Mt CH4/yr     50.207120
                                            Emissions|CO            Mt CO/yr     355.801100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3841.854860
                                            Emissions|CO2|Fossil    Mt CO2/yr   -565.514200
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    437.216617
                                            Emissions|CO2|Biosphere Mt CO2/yr    462.995950
                                            Emissions|CO2|Fossil    Mt CO2/yr  82972.482440
                                            Emissions|N2O           kt N2O/yr  11471.374243
                                            Emissions|SOx           Mt SO2/yr     28.686702

                                                                                       2093  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.168800
                                            Emissions|CH4           Mt CH4/yr     49.803730
                                            Emissions|CO            Mt CO/yr     353.348100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3813.351540
                                            Emissions|CO2|Fossil    Mt CO2/yr   -602.455650
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    434.712103
                                            Emissions|CO2|Biosphere Mt CO2/yr    468.316037
                                            Emissions|CO2|Fossil    Mt CO2/yr  82596.222140
                                            Emissions|N2O           kt N2O/yr  11450.630376
                                            Emissions|SOx           Mt SO2/yr     28.458714

                                                                                       2094  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.154800
                                            Emissions|CH4           Mt CH4/yr     49.400340
                                            Emissions|CO            Mt CO/yr     350.895100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3784.848220
                                            Emissions|CO2|Fossil    Mt CO2/yr   -639.397100
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    432.207589
                                            Emissions|CO2|Biosphere Mt CO2/yr    473.636124
                                            Emissions|CO2|Fossil    Mt CO2/yr  82219.961841
                                            Emissions|N2O           kt N2O/yr  11429.886509
                                            Emissions|SOx           Mt SO2/yr     28.230726

                                                                                       2095  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.140800
                                            Emissions|CH4           Mt CH4/yr     48.996950
                                            Emissions|CO            Mt CO/yr     348.442100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3756.344900
                                            Emissions|CO2|Fossil    Mt CO2/yr   -676.338550
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    429.703076
                                            Emissions|CO2|Biosphere Mt CO2/yr    478.956212
                                            Emissions|CO2|Fossil    Mt CO2/yr  81843.701541
                                            Emissions|N2O           kt N2O/yr  11409.142642
                                            Emissions|SOx           Mt SO2/yr     28.002738

                                                                                       2096  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.126800
                                            Emissions|CH4           Mt CH4/yr     48.593560
                                            Emissions|CO            Mt CO/yr     345.989100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3727.841580
                                            Emissions|CO2|Fossil    Mt CO2/yr   -713.280000
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    427.198562
                                            Emissions|CO2|Biosphere Mt CO2/yr    484.276299
                                            Emissions|CO2|Fossil    Mt CO2/yr  81467.441241
                                            Emissions|N2O           kt N2O/yr  11388.398774
                                            Emissions|SOx           Mt SO2/yr     27.774750


In [9]:
if emissions_run.isnull().any().any():
    raise AssertionError

## Harmonisation

In [10]:
harmonisation_year = 2023
run_checks = True
progress = True
# Sorry Ben, you can adjust for slurm
n_processes = multiprocessing.cpu_count()
# n_processes = None

historical_emissions_file = Path(
    "history_cmip7_scenariomip.csv"
)
aneris_overrides_file = Path(
    "aneris-overrides-global.csv"
)

historical_emissions = load_cmip7_scenariomip_historical_emissions(
    filepath=historical_emissions_file,
    # check_hash=True,
)

# Drop out the model and scenario levels
historical_emissions = historical_emissions.reset_index(
    historical_emissions.index.names.difference(["variable", "region", "unit"]),  # type: ignore # pandas-stubs out of date
    drop=True,
)

# Use gcages naming to match pre-processed outputs.
historical_emissions = update_index_levels_func(
    historical_emissions,
    {
        "variable": lambda x: convert_variable_name(
            x,
            from_convention=SupportedNamingConventions.CMIP7_SCENARIOMIP,
            to_convention=SupportedNamingConventions.GCAGES,
        )
    },
    copy=False,
)

aneris_overrides = load_aneris_overrides_file(aneris_overrides_file)
# Type juggling for mypy: from series to dataframe back to series
# TODO: remove this as it isn't needed for pandas-openscm 0.8.1
aneris_overrides_df = aneris_overrides.to_frame(name="method")
updated_df = update_index_levels_func(
    aneris_overrides_df,
    {
        "variable": lambda x: convert_variable_name(
            x,
            from_convention=SupportedNamingConventions.CMIP7_SCENARIOMIP,
            to_convention=SupportedNamingConventions.GCAGES,
        )
    },
    copy=False,
)
aneris_overrides = updated_df["method"]

harmoniser = AnerisHarmoniser(
    historical_emissions=historical_emissions,
    harmonisation_year=harmonisation_year,
    aneris_overrides=aneris_overrides,
    run_checks=run_checks,
    progress=progress,
    n_processes=n_processes,
)

In [11]:
harmonised_global = harmoniser(emissions_run)
harmonised_global

0it [00:00, ?it/s]

Scenarios to harmonise:   0%|          | 0/1563 [00:00<?, ?it/s]

INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with model_zero
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with constant_ratio
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_ratio_2080
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov
INFO:root:Harmonizing with reduce_offset_2150_cov

                                                                                       2023  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       7.219245
                                            Emissions|CH4           Mt CH4/yr    363.489901
                                            Emissions|CO            Mt CO/yr     774.053434
                                            Emissions|CO2|Biosphere Mt CO2/yr   3627.550667
                                            Emissions|CO2|Fossil    Mt CO2/yr  38712.217040
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    363.489901
                                            Emissions|CO2|Biosphere Mt CO2/yr   3627.550667
                                            Emissions|CO2|Fossil    Mt CO2/yr  38712.217040
                                            Emissions|N2O           kt N2O/yr  11289.003671
                                            Emissions|SOx           Mt SO2/yr     71.902038

                                                                                       2024  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       6.942491
                                            Emissions|CH4           Mt CH4/yr    332.845294
                                            Emissions|CO            Mt CO/yr     758.003015
                                            Emissions|CO2|Biosphere Mt CO2/yr   3249.784994
                                            Emissions|CO2|Fossil    Mt CO2/yr  36639.056595
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    367.799315
                                            Emissions|CO2|Biosphere Mt CO2/yr   3623.447698
                                            Emissions|CO2|Fossil    Mt CO2/yr  39692.457424
                                            Emissions|N2O           kt N2O/yr  11316.687192
                                            Emissions|SOx           Mt SO2/yr     71.832822

                                                                                       2025  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       6.667881
                                            Emissions|CH4           Mt CH4/yr    302.379832
                                            Emissions|CO            Mt CO/yr     741.987254
                                            Emissions|CO2|Biosphere Mt CO2/yr   2872.019322
                                            Emissions|CO2|Fossil    Mt CO2/yr  34582.284727
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    372.122996
                                            Emissions|CO2|Biosphere Mt CO2/yr   3619.344730
                                            Emissions|CO2|Fossil    Mt CO2/yr  40676.220409
                                            Emissions|N2O           kt N2O/yr  11344.301674
                                            Emissions|SOx           Mt SO2/yr     71.762522

                                                                                       2026  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       6.395415
                                            Emissions|CH4           Mt CH4/yr    272.093514
                                            Emissions|CO            Mt CO/yr     726.006152
                                            Emissions|CO2|Biosphere Mt CO2/yr   2494.253650
                                            Emissions|CO2|Fossil    Mt CO2/yr  32541.901436
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    375.746260
                                            Emissions|CO2|Biosphere Mt CO2/yr   3617.835996
                                            Emissions|CO2|Fossil    Mt CO2/yr  41610.361900
                                            Emissions|N2O           kt N2O/yr  11363.408039
                                            Emissions|SOx           Mt SO2/yr     71.287372

                                                                                       2027  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       6.125092
                                            Emissions|CH4           Mt CH4/yr    241.986340
                                            Emissions|CO            Mt CO/yr     710.059709
                                            Emissions|CO2|Biosphere Mt CO2/yr   2116.487978
                                            Emissions|CO2|Fossil    Mt CO2/yr  30517.906723
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    379.380958
                                            Emissions|CO2|Biosphere Mt CO2/yr   3616.327263
                                            Emissions|CO2|Fossil    Mt CO2/yr  42547.819876
                                            Emissions|N2O           kt N2O/yr  11382.460747
                                            Emissions|SOx           Mt SO2/yr     70.809287

                                                                                       2028  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.856913
                                            Emissions|CH4           Mt CH4/yr    212.058311
                                            Emissions|CO            Mt CO/yr     694.147925
                                            Emissions|CO2|Biosphere Mt CO2/yr   1738.722306
                                            Emissions|CO2|Fossil    Mt CO2/yr  28510.300587
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    383.027092
                                            Emissions|CO2|Biosphere Mt CO2/yr   3614.818529
                                            Emissions|CO2|Fossil    Mt CO2/yr  43488.594337
                                            Emissions|N2O           kt N2O/yr  11401.459798
                                            Emissions|SOx           Mt SO2/yr     70.328269

                                                                                       2029  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.590877
                                            Emissions|CH4           Mt CH4/yr    182.309426
                                            Emissions|CO            Mt CO/yr     678.270799
                                            Emissions|CO2|Biosphere Mt CO2/yr   1360.956634
                                            Emissions|CO2|Fossil    Mt CO2/yr  26519.083028
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    386.684660
                                            Emissions|CO2|Biosphere Mt CO2/yr   3613.309796
                                            Emissions|CO2|Fossil    Mt CO2/yr  44432.685284
                                            Emissions|N2O           kt N2O/yr  11420.405192
                                            Emissions|SOx           Mt SO2/yr     69.844316

                                                                                       2030  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.326986
                                            Emissions|CH4           Mt CH4/yr    152.739685
                                            Emissions|CO            Mt CO/yr     662.428333
                                            Emissions|CO2|Biosphere Mt CO2/yr    983.190961
                                            Emissions|CO2|Fossil    Mt CO2/yr  24544.254046
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    390.353663
                                            Emissions|CO2|Biosphere Mt CO2/yr   3611.801062
                                            Emissions|CO2|Fossil    Mt CO2/yr  45380.092715
                                            Emissions|N2O           kt N2O/yr  11439.296929
                                            Emissions|SOx           Mt SO2/yr     69.357429

                                                                                       2031  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.216459
                                            Emissions|CH4           Mt CH4/yr    148.459066
                                            Emissions|CO            Mt CO/yr     653.601323
                                            Emissions|CO2|Biosphere Mt CO2/yr    711.303829
                                            Emissions|CO2|Fossil    Mt CO2/yr  23389.075123
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    393.346369
                                            Emissions|CO2|Biosphere Mt CO2/yr   3569.990668
                                            Emissions|CO2|Fossil    Mt CO2/yr  46237.155490
                                            Emissions|N2O           kt N2O/yr  11435.538768
                                            Emissions|SOx           Mt SO2/yr     68.324805

                                                                                       2032  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       5.106714
                                            Emissions|CH4           Mt CH4/yr    144.202042
                                            Emissions|CO            Mt CO/yr     644.792892
                                            Emissions|CO2|Biosphere Mt CO2/yr    439.416697
                                            Emissions|CO2|Fossil    Mt CO2/yr  22243.169769
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    396.347811
                                            Emissions|CO2|Biosphere Mt CO2/yr   3528.180274
                                            Emissions|CO2|Fossil    Mt CO2/yr  47097.174979
                                            Emissions|N2O           kt N2O/yr  11431.768329
                                            Emissions|SOx           Mt SO2/yr     67.286787

                                                                               ...  \
model             scenario           region variable                unit       ...
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr   ...
                                            Emissions|CH4           Mt CH4/yr  ...
                                            Emissions|CO            Mt CO/yr   ...
                                            Emissions|CO2|Biosphere Mt CO2/yr  ...
                                            Emissions|CO2|Fossil    Mt CO2/yr  ...
...                                                                            ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr  ...
                                            Emissions|CO2|Biosphere Mt CO2/yr  ...
                                            Emissions|CO2|Fossil    Mt CO2/yr  ...
                                            Emissions|N2O           kt N2O/yr  ...
                                            Emissions|SOx           Mt SO2/yr  ...

                                                                                       2091  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.196800
                                            Emissions|CH4           Mt CH4/yr     50.610510
                                            Emissions|CO            Mt CO/yr     358.254100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3349.778041
                                            Emissions|CO2|Fossil    Mt CO2/yr   -528.572750
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    439.721131
                                            Emissions|CO2|Biosphere Mt CO2/yr    907.012403
                                            Emissions|CO2|Fossil    Mt CO2/yr  83348.742740
                                            Emissions|N2O           kt N2O/yr  11492.118111
                                            Emissions|SOx           Mt SO2/yr     28.914690

                                                                                       2092  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.182800
                                            Emissions|CH4           Mt CH4/yr     50.207120
                                            Emissions|CO            Mt CO/yr     355.801100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3330.098114
                                            Emissions|CO2|Fossil    Mt CO2/yr   -565.514200
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    437.216617
                                            Emissions|CO2|Biosphere Mt CO2/yr    904.716616
                                            Emissions|CO2|Fossil    Mt CO2/yr  82972.482440
                                            Emissions|N2O           kt N2O/yr  11471.374243
                                            Emissions|SOx           Mt SO2/yr     28.686702

                                                                                       2093  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.168800
                                            Emissions|CH4           Mt CH4/yr     49.803730
                                            Emissions|CO            Mt CO/yr     353.348100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3310.418186
                                            Emissions|CO2|Fossil    Mt CO2/yr   -602.455650
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    434.712103
                                            Emissions|CO2|Biosphere Mt CO2/yr    902.420830
                                            Emissions|CO2|Fossil    Mt CO2/yr  82596.222140
                                            Emissions|N2O           kt N2O/yr  11450.630376
                                            Emissions|SOx           Mt SO2/yr     28.458714

                                                                                       2094  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.154800
                                            Emissions|CH4           Mt CH4/yr     49.400340
                                            Emissions|CO            Mt CO/yr     350.895100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3290.738258
                                            Emissions|CO2|Fossil    Mt CO2/yr   -639.397100
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    432.207589
                                            Emissions|CO2|Biosphere Mt CO2/yr    900.125044
                                            Emissions|CO2|Fossil    Mt CO2/yr  82219.961841
                                            Emissions|N2O           kt N2O/yr  11429.886509
                                            Emissions|SOx           Mt SO2/yr     28.230726

                                                                                       2095  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.140800
                                            Emissions|CH4           Mt CH4/yr     48.996950
                                            Emissions|CO            Mt CO/yr     348.442100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3271.058330
                                            Emissions|CO2|Fossil    Mt CO2/yr   -676.338550
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    429.703076
                                            Emissions|CO2|Biosphere Mt CO2/yr    897.829258
                                            Emissions|CO2|Fossil    Mt CO2/yr  81843.701541
                                            Emissions|N2O           kt N2O/yr  11409.142642
                                            Emissions|SOx           Mt SO2/yr     28.002738

                                                                                       2096  \
model             scenario           region variable                unit
AIM/CGE 2.0       SSP1-19            World  Emissions|BC            Mt BC/yr       2.126800
                                            Emissions|CH4           Mt CH4/yr     48.593560
                                            Emissions|CO            Mt CO/yr     345.989100
                                            Emissions|CO2|Biosphere Mt CO2/yr  -3251.378402
                                            Emissions|CO2|Fossil    Mt CO2/yr   -713.280000
...                                                                                     ...
WITCH-GLOBIOM 4.4 CD-LINKS-No-Policy World  Emissions|CH4           Mt CH4/yr    427.198562
                                            Emissions|CO2|Biosphere Mt CO2/yr    895.533472
                                            Emissions|CO2|Fossil    Mt CO2/yr  81467.441241
                                            Emissions|N2O           kt N2O/yr  11388.398774
                                            Emissions|SOx           Mt SO2/yr     27.774750


## Infilling

In [14]:
# TODO: discuss - we probably want to use a better infilling database.
# For the FOD, this will be fine.
# Have to use https://zenodo.org/records/20566343
infilling_file = Path("infilling_db_cmip7_scenariomip_20566343.csv")
# Messy, but basically a secondary infilling file for minor GHGs
ghg_inversion_file = Path("cmip7_ghg_inversions.csv")

PI_YEAR = 1750
HARMONISATION_YEAR = 2023

ur = openscm_units.unit_registry

infilling_db = load_cmip7_scenariomip_infilling_db(
    filepath=infilling_file,
    check_hash=False,  # TODO: update when available
)

# CMIP7 GHG inversions
cmip7_ghg_inversions = load_cmip7_scenariomip_ghg_inversions(
    filepath=ghg_inversion_file,
)
# History
historical_emissions = load_cmip7_scenariomip_historical_emissions(
    filepath=historical_emissions_file,
    check_hash=False,
)

# Use gcages naming convention.
infilling_db = update_index_levels_func(
    infilling_db,
    {
        "variable": lambda x: convert_variable_name(
            x,
            from_convention=SupportedNamingConventions.CMIP7_SCENARIOMIP,
            to_convention=SupportedNamingConventions.GCAGES,
        )
    },
    copy=False,
)
cmip7_ghg_inversions = update_index_levels_func(
    cmip7_ghg_inversions,
    {
        "variable": lambda x: convert_variable_name(
            x,
            from_convention=SupportedNamingConventions.OPENSCM_RUNNER,
            to_convention=SupportedNamingConventions.GCAGES,
        )
    },
    copy=False,
)
historical_emissions = update_index_levels_func(
    historical_emissions,
    {
        "variable": lambda x: convert_variable_name(
            x,
            from_convention=SupportedNamingConventions.CMIP7_SCENARIOMIP,
            to_convention=SupportedNamingConventions.GCAGES,
        )
    },
    copy=False,
)

assert_harmonised(
    infilling_db,
    history=historical_emissions.reset_index(
        level=[
            lvl
            for lvl in ["model", "scenario"]
            if lvl in historical_emissions.index.names
        ],
        drop=True,
    ),
    harmonisation_time=HARMONISATION_YEAR,
    history_unit_level="unit",
    ur=ur,
)

# Notes: currently this uses RMSClosest under the hood.
# That's probably not a bad decision, and avoids the OC-BC decoupling from AR6.
# We should check though and make an active, rather than passive decision.
# We likely also want to use an updated infilling DB rather than the ScenarioMIP one,
# which was just whatever scenarios we had at the time.
infiller = CMIP7ScenarioMIPInfiller(
    infilling_db=infilling_db,
    historical_emissions=historical_emissions,
    cmip7_ghg_inversions=cmip7_ghg_inversions,
    harmonisation_year=HARMONISATION_YEAR,
    pre_industrial_year=PI_YEAR,
    run_checks=True,
    ur=ur,
)

In [ ]:
complete = infiller(harmonised_global)
# complete.to_feather("complete.feather")
complete.to_parquet("sci_emissions_complete.parquet.gzip", compression="gzip")
complete

/Users/znicholls/Documents/repos-agcec/ar7-ch5-ensemble/.pixi/envs/default/lib/python3.11/site-packages/jwt/api_jwt.py:147: InsecureKeyLengthWarning: The HMAC key is 20 bytes long, which is below the minimum recommended length of 32 bytes for SHA256. See RFC 7518 Section 3.2.
  return self._jws.encode(
/Users/znicholls/Documents/repos-agcec/ar7-ch5-ensemble/.pixi/envs/default/lib/python3.11/site-packages/fastapi/testclient.py:1: StarletteDeprecationWarning: Using `httpx` with `starlette.testclient` is deprecated; install `httpx2` instead.
  from starlette.testclient import TestClient as TestClient  # noqa
[WARNING] 18:37:34 - pint.util: Redefining 'C' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'N' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'NOX' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'gNOX' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'tNOX' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'S' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'yr' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'a' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'h' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'd' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'degreeC' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'degreeF' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'kt' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'Tt' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 18:37:34 - pint.util: Redefining 'ppm' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)